<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.protoc

namespace GPBMetadata;

class Api
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a650a0a6170692e70726f746f63120361706922160a0548656c6c6f120d" .
            "0a0568656c6c6f18012001280932320a0c48656c6c6f5365727669636512" .
            "220a0853617948656c6c6f120a2e6170692e48656c6c6f1a0a2e6170692e" .
            "48656c6c6f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

